name: Survivalweapons
version: '${version}'
main: kro.dodoworld.survivalweapons.Survivalweapons
description: Survivalweapons Sbe Edition.
author: _dodoman
api-version: 1.18
commands:
  sbwitem:
    description: Main Command For Survivalweapons Plugin.
    aliases:
      - sbw
    usage: /<command> <args>