name: Survivalweapons
version: '${version}'
main: kro.dodoworld.survivalweapons.Survivalweapons
description: Only for _dodoman's server.
author: _dodoman
api-version: 1.19
commands:
  switem:
    description: Main command for Survivalweapons plugin.
    permission: survivalweapons.items.give
    aliases:
      - sw
      - survivalweaponsitem
    usage: /<command> <item_name>

permissions:
  survivalweapons.*:
    description: Gives access to all Survivalweapons commands.
    children:
      survivalweapons.items.give: true

  survivalweapons.items.give:
    description: Allows you to get items with /switem command.
    default: op