name: Survivalweapons
version: '${version}'
main: kro.dodoworld.survivalweapons.Survivalweapons
description: Only For _dodoman's Server.
author: _dodoman
api-version: 1.18
commands:
  switem:
    description: Main Command For Survivalweapons Plugin.
    aliases:
      - sw
    usage: /<command> <args>