name: Survivalweapons
version: '${version}'
main: kro.dodoworld.survivalweapons.Survivalweapons
description: Only For _dodoman's Server.
author: _dodoman
api-version: 1.19
commands:
  switem:
    description: Main Command For Survivalweapons Plugin.
    aliases:
      - sw
      - survivalweaponsitem
    usage: /<command> <item_name>